set_property PACKAGE_PIN G19 [get_ports {vga_R}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_R}]
set_property PACKAGE_PIN H19 [get_ports {vga_R}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_R}]
set_property PACKAGE_PIN J19 [get_ports {vga_R}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_R}]
set_property PACKAGE_PIN N19 [get_ports {vga_R}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_R}]
set_property PACKAGE_PIN N18 [get_ports {vga_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_B}]
set_property PACKAGE_PIN L18 [get_ports {vga_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_B}]
set_property PACKAGE_PIN K18 [get_ports {vga_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_B}]
set_property PACKAGE_PIN J18 [get_ports {vga_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_B}]
set_property PACKAGE_PIN J17 [get_ports {vga_G}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_G}]
set_property PACKAGE_PIN H17 [get_ports {vga_G}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_G}]
set_property PACKAGE_PIN G17 [get_ports {vga_G}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_G}]
set_property PACKAGE_PIN D17 [get_ports {vgaG}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_G}]
set_property PACKAGE_PIN P19 [get_ports vga_h_sync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_h_sync]
set_property PACKAGE_PIN R19 [get_ports vga_v_sync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_v_sync]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN T17 [get_ports quadA]
set_property IOSTANDARD LVCMOS33 [get_ports quadA]
set_property PACKAGE_PIN W19 [get_ports quadB]
set_property IOSTANDARD LVCMOS33 [get_ports quadB]

set_property SEVERITY {Warning} [get_drc_checks NSTD-1]

set_property SEVERITY {Warning} [get_drc_checks UCIO-1]