# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab113/lab113.cache/wt} [current_project]
set_property parent.project_path {D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab113/lab113.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files {{d:/Jack/NTHU/2018_spring/LD exp/Lab11/lab9_3/out.coe}}
read_ip -quiet {{d:/Jack/NTHU/2018_spring/LD exp/Lab11/lab113/lab113.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Jack/NTHU/2018_spring/LD exp/Lab11/lab113/lab113.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc}}]
set_property is_locked true [get_files {{d:/Jack/NTHU/2018_spring/LD exp/Lab11/lab113/lab113.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

read_verilog -library xil_defaultlib {
  {D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab9_3/mem_addr_gen.v}
  {D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab9_3/vga.v}
  {D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab9_3/clock_divisor.v}
  {D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab113/lab113.srcs/sources_1/new/LFSR.v}
  {D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab9_3/top.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab9_3/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Jack/NTHU/2018_spring/LD exp/Lab11/lab9_3/Basys3_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
