set_property PACKAGE_PIN W5 [get_ports {CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {CLK}]

set_property PACKAGE_PIN U16 [get_ports {ASCII[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[0]}]
set_property PACKAGE_PIN E19 [get_ports {ASCII[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[1]}]
set_property PACKAGE_PIN U19 [get_ports {ASCII[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[2]}]
set_property PACKAGE_PIN V19 [get_ports {ASCII[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[3]}]
set_property PACKAGE_PIN W18 [get_ports {ASCII[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[4]}]
set_property PACKAGE_PIN U15 [get_ports {ASCII[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[5]}]
set_property PACKAGE_PIN U14 [get_ports {ASCII[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[6]}]
set_property PACKAGE_PIN V14 [get_ports {ASCII[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[7]}]
set_property PACKAGE_PIN V13 [get_ports {ASCII[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[8]}]
set_property PACKAGE_PIN V3 [get_ports {ASCII[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ASCII[9]}]

set_property PACKAGE_PIN L1 [get_ports {shift}]
set_property IOSTANDARD LVCMOS33 [get_ports {shift}]
set_property PACKAGE_PIN N3 [get_ports {caps}]
set_property IOSTANDARD LVCMOS33 [get_ports {caps}]

set_property PACKAGE_PIN T17 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]

set_property PACKAGE_PIN W7 [get_ports {display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]
set_property PACKAGE_PIN W6 [get_ports {display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property PACKAGE_PIN U8 [get_ports {display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property PACKAGE_PIN V8 [get_ports {display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property PACKAGE_PIN U5 [get_ports {display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property PACKAGE_PIN V5 [get_ports {display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property PACKAGE_PIN U7 [get_ports {display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]
set_property PACKAGE_PIN V7 [get_ports {display[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[7]}]

set_property PACKAGE_PIN W4 [get_ports {ssd_ctl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[3]}]
set_property PACKAGE_PIN V4 [get_ports {ssd_ctl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[2]}]
set_property PACKAGE_PIN U4 [get_ports {ssd_ctl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[1]}]
set_property PACKAGE_PIN U2 [get_ports {ssd_ctl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[0]}]

set_property PACKAGE_PIN C17 [get_ports {PS2_CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2_CLK}]
set_property PACKAGE_PIN B17 [get_ports {PS2_DATA}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2_DATA}]

set_property SEVERITY {Warning} [get_drc_checks NSTD-1]

set_property SEVERITY {Warning} [get_drc_checks UCIO-1]