# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Jack/NTHU/2018_spring/LD exp/Lab04/lab04pre/lab04pre.cache/wt} [current_project]
set_property parent.project_path {D:/Jack/NTHU/2018_spring/LD exp/Lab04/lab04pre/lab04pre.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {D:/Jack/NTHU/2018_spring/LD exp/Lab04/lab04pre/lab04pre.srcs/sources_1/new/shifter.v}
  {D:/Jack/NTHU/2018_spring/LD exp/Lab04/lab04pre/lab04pre.srcs/sources_1/new/frequency.v}
  {D:/Jack/NTHU/2018_spring/LD exp/Lab04/lab04pre/lab04pre.srcs/sources_1/new/lab04pre.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Jack/NTHU/2018_spring/LD exp/Lab04/lab04pre/lab04pre.srcs/constrs_1/new/lab04pre_XDC.xdc}}
set_property used_in_implementation false [get_files {{D:/Jack/NTHU/2018_spring/LD exp/Lab04/lab04pre/lab04pre.srcs/constrs_1/new/lab04pre_XDC.xdc}}]


synth_design -top lab04pre -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab04pre.dcp

catch { report_utilization -file lab04pre_utilization_synth.rpt -pb lab04pre_utilization_synth.pb }
